In [1]:
try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False

TRAIN_FLAG = False

In [2]:
import torch
!nvcc --version
TORCH_VERSION = ".".join(torch.__version__.split(".")[:2])
CUDA_VERSION = torch.__version__.split("+")[-1]
print("torch: ", TORCH_VERSION, "; cuda: ", CUDA_VERSION)

torch:  1.13 ; cuda:  cpu


"nvcc" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [3]:
!nvidia-smi

"nvidia-smi" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [9]:
import os
if IN_COLAB or 'LessPerson-8' not in os.listdir('../../datasets'):
    !pip install roboflow

    from roboflow import Roboflow
    rf = Roboflow(api_key="FlkxEvR1HdCJepitvMdT")
    project = rf.workspace("-tvhts").project("lessperson")
    dataset = project.version(8).download("yolov8")


In [8]:
if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
else:
    import shutil
    shutil.move('LessPerson-8', '../../datasets/')

In [7]:
from ultralytics import YOLO
if IN_COLAB:
    datasets_path = "/content"
else:
    datasets_path = "../../datasets"

if TRAIN_FLAG:
    model = YOLO('yolov8n.pt')
    results = model.train(
       data=f'{datasets_path}/LessPerson-8/data.yaml',
       imgsz=416,
       epochs=128,
       batch=64,
       name='yolov8n_Person_Detection')

In [8]:
if IN_COLAB:
    from shutil import move

    move("/content/runs",'/content/drive/MyDrive/Models')

In [9]:
if IN_COLAB:
    from ultralytics import YOLO
    import os
    from google.colab.patches import cv2_imshow
    from cv2 import imread
else:
    from ultralytics import YOLO
    import os
    from cv2 import imread, imshow, waitKey, destroyAllWindows

In [10]:
if TRAIN_FLAG:
    success = model.export(format="onnx")

In [11]:
import os
print(os.listdir("."))

['yolov8n_Person_Detection2', 'YOLO_Human_Detection_Training.ipynb']


In [12]:
if IN_COLAB:
    im = imread("drive/MyDrive/Models/runs/detect/yolov8n_Person_Detection2/results.png")
    cv2_imshow(im)
else:
    im = imread("yolov8n_Person_Detection2/results.png")
    imshow("name", im)
    waitKey(0)
    destroyAllWindows()


In [13]:
import cv2
def box_label(image, box, label='', color=(128, 128, 128), txt_color=(255, 255, 255)):
  lw = max(round(sum(image.shape) / 2 * 0.003), 2)
  p1, p2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))
  cv2.rectangle(image, p1, p2, color, thickness=lw, lineType=cv2.LINE_AA)
  if label:
    tf = max(lw - 1, 1)  # font thickness
    w, h = cv2.getTextSize(label, 0, fontScale=lw / 3, thickness=tf)[0]  # text width, height
    outside = p1[1] - h >= 3
    p2 = p1[0] + w, p1[1] - h - 3 if outside else p1[1] + h + 3
    cv2.rectangle(image, p1, p2, color, -1, cv2.LINE_AA)  # filled
    cv2.putText(image,
                label, (p1[0], p1[1] - 2 if outside else p1[1] + h + 2),
                0,
                lw / 3,
                txt_color,
                thickness=tf,
                lineType=cv2.LINE_AA)


def plot_bboxes(image, boxes, labels=[], colors=[], score=True, conf=None):

  #Define COCO Labels
  if labels == []:
    labels = {0:u'__background__', 1: u'Person'}
  #Define colors
  if colors == []:
    colors = [(89, 161, 197),(67, 161, 255),(19, 222, 24),(186, 55, 2),(167, 146, 11),(190, 76, 98),(130, 172, 179),(115, 209, 128),(204, 79, 135),(136, 126, 185),(209, 213, 45),(44, 52, 10),(101, 158, 121),(179, 124, 12),(25, 33, 189),(45, 115, 11),(73, 197, 184),(62, 225, 221),(32, 46, 52),(20, 165, 16),(54, 15, 57),(12, 150, 9),(10, 46, 99),(94, 89, 46),(48, 37, 106),(42, 10, 96),(7, 164, 128),(98, 213, 120),(40, 5, 219),(54, 25, 150),(251, 74, 172),(0, 236, 196),(21, 104, 190),(226, 74, 232),(120, 67, 25),(191, 106, 197),(8, 15, 134),(21, 2, 1),(142, 63, 109),(133, 148, 146),(187, 77, 253),(155, 22, 122),(218, 130, 77),(164, 102, 79),(43, 152, 125),(185, 124, 151),(95, 159, 238),(128, 89, 85),(228, 6, 60),(6, 41, 210),(11, 1, 133),(30, 96, 58),(230, 136, 109),(126, 45, 174),(164, 63, 165),(32, 111, 29),(232, 40, 70),(55, 31, 198),(148, 211, 129),(10, 186, 211),(181, 201, 94),(55, 35, 92),(129, 140, 233),(70, 250, 116),(61, 209, 152),(216, 21, 138),(100, 0, 176),(3, 42, 70),(151, 13, 44),(216, 102, 88),(125, 216, 93),(171, 236, 47),(253, 127, 103),(205, 137, 244),(193, 137, 224),(36, 152, 214),(17, 50, 238),(154, 165, 67),(114, 129, 60),(119, 24, 48),(73, 8, 110)]

  #plot each boxes
  for box in boxes:
    #add score in label if score=True
    if score :
      label = labels[int(box[-1])+1] + " " + str(round(100 * float(box[-2]),1)) + "%"
    else :
      label = labels[int(box[-1])+1]
    #filter every box under conf threshold if conf threshold setted
    if conf :
      if box[-2] > conf:
        color = colors[int(box[-1])]
        box_label(image, box, label, color)
    else:
      color = colors[int(box[-1])]
      box_label(image, box, label, color)

  #show image
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

  try:
    import google.colab
    IN_COLAB = True
  except:
    IN_COLAB = False

  if IN_COLAB:
    cv2_imshow(image) #if used in Colab
  else :
    cv2.imshow("",image) #if used in Python
    waitKey(0)
    destroyAllWindows()

In [15]:
if IN_COLAB:
    datasets_path = "/content"
    model_path = "drive/MyDrive/Models/runs/detect"
else:
    datasets_path = "../../datasets"
    model_path = ""

images_path = os.listdir(f'{datasets_path}/LessPerson-8/test/images')
model = YOLO(f'{model_path}yolov8n_Person_Detection2/weights/best.pt')
for img in images_path:
    results = model.predict(

    source=f'{datasets_path}/LessPerson-8/test/images/{img}')
    #source="../1452546327-8e5189cb2eacc8b9b2c808a53449904c.jpeg")
    im = imread(f"{datasets_path}/LessPerson-8/test/images/{img}")
    plot_bboxes(im, results[0].boxes.boxes, score=True)
    break
print(results[0].boxes.boxes)
for i in results[0].boxes.boxes:
  print(i)



image 1/1 C:\Users\Xtrabatya\PycharmProjects\HumanTracking\dev\src\models\..\1452546327-8e5189cb2eacc8b9b2c808a53449904c.jpeg: 416x288 3 Persons, 306.2ms
Speed: 8.2ms preprocess, 306.2ms inference, 7.2ms postprocess per image at shape (1, 3, 416, 416)
WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


tensor([[7.4772e+01, 7.9816e+01, 1.7264e+02, 3.7640e+02, 9.2758e-01, 0.0000e+00],
        [1.4499e+02, 2.8218e+01, 2.6464e+02, 3.7766e+02, 8.9157e-01, 0.0000e+00],
        [2.3636e+02, 4.5747e+02, 3.1259e+02, 5.0000e+02, 3.2046e-01, 0.0000e+00]])
tensor([ 74.7716,  79.8164, 172.6383, 376.3986,   0.9276,   0.0000])
tensor([144.9926,  28.2179, 264.6388, 377.6558,   0.8916,   0.0000])
tensor([2.3636e+02, 4.5747e+02, 3.1259e+02, 5.0000e+02, 3.2046e-01, 0.0000e+00])
